version: '3.8'

services:
  db:
    image: postgres:15
    container_name: subastas_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subastas_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - subasta-network

  backend:
    build: ./backend
    container_name: subastas_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/subastas_db
    networks:
      - subasta-network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  pgadmin:  # ðŸ‘ˆ AsegÃºrate que este bloque estÃ¡ aquÃ­
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - subasta-network

volumes:
  postgres_data:

networks:
  subasta-network:
    driver: bridge

